### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by mpiekarski78** [GetRektBoy724/SharpUnhooker#3]
With GameGuard:

[+++] NTDLL.DLL IS UNHOOKED!
[+++] NTDLL.DLL EXPORTS ARE CLEANSED!
[+++] KERNEL32.DLL IS UNHOOKED!
[+++] KERNEL32.DLL EXPORTS ARE CLEANSED!
[+++] KERNEL32.DLL IMPORTS ARE CLEANSED!
[+++] KERNELBASE.DLL IS UNHOOKED!
[+++] KERNELBASE.DLL EXPORTS ARE CLEANSED!
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.SpanHelpers.IndexOf(Byte ByRef, Byte, Int32)
   at System.String.Ctor(SByte*)
   at System.Runtime.InteropServices.Marshal.PtrToStringAnsi(IntPtr)
   at SharpUnhooker.IATUnhooker(System.String)
   at SharpUnhooker.Main()

**Comment by nickswink** [comment]
I have same issue

**Comment by soufianetahiri** [comment]
try to exclude NtQueueApcThread from the IAT cleaner (this what caused the issue for me)
